### ISSUE TITLE
Weird malformed URL

### ISSUE THREAD

**Issue by arthuro555** [crazy-max/ghaction-github-pages#25]
I tried to make an auto jsdoc build and deployement workflow using this tool but when your tool was running it tried to connect to https://***/github.com instead of https://github.com.
![malformated url](https://user-images.githubusercontent.com/19349038/69093038-f5c04700-0a4d-11ea-8fde-fa9b423b13ff.PNG)
You can check my worflow on my repo arthuro555/gdevelop-server to see if the error comes from me.

**Comment by crazy-max** [comment]
@arthuro555 

> tried to connect to https://***/github.com instead of https://github.com.

That's because `GITHUB_PAT` is [injected in the repo URL](https://github.com/crazy-max/ghaction-github-pages/blob/master/src/main.ts#L26-L37).

About this error, it looks like your `secrets.TokenRefreshGHPages` contains a blank space somewhere. Can you check this first ?

You can also remove [this line](https://github.com/arthuro555/gdevelop-server/blob/master/.github/workflows/docbuild.yml#L33) as it's the same repo.

**Comment by arthuro555** [comment]
Oh, yes, my bad. My apologizes for wasting your time.

**Comment by crazy-max** [comment]
@arthuro555 No problem, glad you fixed it. I will add a check on this to avoid this kind of error in the future.
